name: .NET Test Api

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    strategy:
      matrix:
        configuration: [Debug, Release]

    runs-on: ubuntu-latest

    env:
      Solution_Name: test.sln
      Test_Project_Path: test.UnitTests

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    # Install the .NET Core workload
    - name: Install .NET Core
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    - name: Build
      run: dotnet build -c Release

    # Execute all unit tests in the solution
    - name: Execute unit tests
      run: |
          dotnet test -c Release \
            /p:CollectCoverage=true /p:CoverletOutputFormat=opencover -p:CoverletOutput=TestResults

    - name: Publish Test Results
      uses: EnricoMi/publish-unit-test-result-action@v2
      if: always()
      with:
        files: |
            ${{env.Test_Project_Path}}/TestResults/*.xml"

